[package]
name = "lvchat-server"
version = "0.1.0"
authors = ["avonarret"]
edition = "2018"

[dependencies]
flume = "0.7"
parking_lot = "0.10"

structopt = "0.3"

log = "*"
flexi_logger = "0.15"

lvchat-core = { path = "../lvchat-core" }
